const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stages=['Idea','Research','Script','Record','Edit','Ready','Published'];
let state={videos:[],channel:{}}, view='overview', tab='brief', month=new Date(), creatingStage='Idea', dirty=false, busy=false, renderedId='';
const active=()=>state.videos.filter(v=>!v.archived&&!v.deleted);
const pretty=d=>d?new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'Unscheduled';
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500)}
async function api(path,data){const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x}
function card(v,compact=false){let done=v.tasks.filter(t=>t.done).length;return `<a class="video-card" draggable="true" data-video="${v.id}" href="#video/${v.id}"><div class="card-body"><div class="card-top">${v.pillar?`<span class="pill">${esc(v.pillar)}</span>`:''}<span class="stage">${v.sponsored==='Yes'?'Sponsored · ':''}${esc(v.stage)}</span></div><h3>${esc(v.title)}</h3>${!compact&&v.hook?`<p>${esc(v.hook)}</p>`:''}<div class="card-footer"><span>${pretty(v.date)}</span><span>${done}/${v.tasks.length} tasks</span></div></div></a>`}
function heading(title,sub='',action=true){return `<div class="page-heading"><div><h1>${title}</h1>${sub?`<p class="sub">${sub}</p>`:''}</div>${action?'<button class="primary" data-create>New video</button>':''}</div>`}
function taskRows(tasks,scope){return tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><input type="checkbox" aria-label="${esc(t.text)}" data-task="${i}" data-scope="${scope}" ${t.done?'checked':''}><span>${esc(t.text)}</span><button class="remove" aria-label="Remove task" data-remove="${i}" data-scope="${scope}">×</button></div>`).join('')}
function videos(){return heading('Videos')+`<div class="filters"><input id="filter" placeholder="Filter videos…" aria-label="Filter videos"><span class="muted">${active().length} videos · ${stages.length} stages</span></div><div class="board">${stages.map(s=>`<section class="column" data-drop-stage="${s}"><h3>${s}<span>${active().filter(v=>v.stage===s).length}</span></h3>${active().filter(v=>v.stage===s).map(v=>card(v,true)).join('')}<button class="column-add" data-create data-stage="${s}">Add video</button></section>`).join('')}</div>`}
function field(label,key,value,type='textarea'){return `<label>${label}${type==='textarea'?`<textarea data-field="${key}">${esc(value)}</textarea>`:`<input data-field="${key}" type="${type}" value="${esc(value)}">`}</label>`}
function detail(v){let done=v.tasks.filter(t=>t.done).length;return `<a class="back" href="#videos">← Videos</a><div class="page-heading"><div style="flex:1"><div class="eyebrow">Video ${v.deleted?'· In trash':v.archived?'· Archived':''}</div><input class="detail-title" data-field="title" value="${esc(v.title)}" maxlength="250" aria-label="Video title"></div><span class="save-state">Saved</span><button class="primary" id="save-video">Save changes</button></div><div class="detail-layout"><section><div class="tabs">${[['brief','Brief'],['script','Script'],['packaging','Packaging'],['tasks','Checklist'],['review','Review'],['notes','Notes']].map(([k,n])=>`<button data-tab="${k}" class="${tab===k?'selected':''}">${n}</button>`).join('')}</div><div class="panel">${tab==='notes'?NB.videoNotes(v):tab==='review'?review(v):tab==='brief'?field('Why might this video work?','hypothesis',v.hypothesis)+field('Hook','hook',v.hook)+field('Research, links & production notes','notes',v.notes):tab==='script'?'<div class="eyebrow">Script (Markdown)</div><textarea class="script" data-field="script" aria-label="Video script" placeholder="Write script…">'+esc(v.script)+'</textarea>':tab==='packaging'?field('Title candidates · one per line','titles',v.titles)+field('Thumbnail concept & asset links','thumbnail',v.thumbnail)+NB.videoImages(v):`<div class="section-heading" style="margin-top:0"><h2>Checklist</h2><span class="muted">${done} of ${v.tasks.length} complete</span></div><div class="progress"><div style="width:${v.tasks.length?done/v.tasks.length*100:0}%"></div></div>${taskRows(v.tasks,v.id)}<form class="inline-add" data-add-task="${v.id}"><input required name="task" placeholder="Add a production task…" aria-label="New production task"><button class="primary">Add</button></form>`}</div></section><aside class="panel" style="align-self:start"><div class="eyebrow">Details</div><label>Production stage<select data-field="stage">${stages.map(s=>`<option ${v.stage===s?'selected':''}>${s}</option>`).join('')}</select></label>${field('Publish date','date',v.date,'date')}${field('Content pillar','pillar',v.pillar,'text')}${choice('Sponsored video','sponsored',v.sponsored||'No',['No','Yes'])}${field('Sponsor','sponsor',v.sponsor,'text')}${choice('Sponsor status','sponsorStatus',v.sponsorStatus||'Not started',['Not started','Outreach','Negotiating','Contract agreed','Brief received','Draft sent','Changes requested','Approved','Published','Invoiced','Paid'])}${v.deleted?'<button class="secondary" id="restore-video">Restore video</button>':`<button class="secondary" id="archive-video">${v.archived?'Restore project':'Archive project'}</button><button class="secondary danger" id="delete-video">Delete video</button>`}</aside></div>`}
function calendar(){let year=month.getFullYear(),m=month.getMonth(),start=(new Date(year,m,1).getDay()+6)%7,total=new Date(year,m+1,0).getDate();let cells=Array.from({length:Math.ceil((start+total)/7)*7},(_,i)=>{let day=i-start+1;if(day<1||day>total)return '<div class="day blank"></div>';let d=localDate(new Date(year,m,day));return `<div class="day ${d===localDate(new Date())?'today':''}"><span>${day}</span>${active().filter(v=>v.date===d).map(v=>`<a class="calendar-event" href="#video/${v.id}">${esc(v.title)}<br><span>${esc(v.stage)}</span></a>`).join('')}</div>`});return heading('Calendar')+`<div class="section-heading"><div class="calendar-toolbar"><button class="secondary" data-month="-1" aria-label="Previous month">←</button><h2>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button class="secondary" data-month="1" aria-label="Next month">→</button></div><button class="secondary" id="month-today">Today</button></div><div class="calendar"><div class="weekdays">${['MON','TUE','WED','THU','FRI','SAT','SUN'].map(x=>`<div>${x}</div>`).join('')}</div><div class="days">${cells.join('')}</div></div><p class="notice">${active().filter(v=>!v.date).length} videos without a publish date. Set dates in each video’s project details.</p>`}
function channel(){const c=state.channel;return heading('Channel','',false)+`<div class="channel-grid"><section class="panel"><div class="section-heading" style="margin-top:0"><h2>Settings</h2><button class="primary" id="save-channel">Save changes</button></div>${field('Channel name','name',c.name,'text')}${field('Purpose and audience','mission',c.mission)}${field('Content pillars · one per line','pillars',c.pillars)}${field('Strategy, recurring formats & retrospective','notes',c.notes)}<span class="save-state">Saved</span></section><section><div class="panel"><h2>Tasks</h2>${taskRows(c.tasks||[],'channel')}<form class="inline-add" data-add-task="channel"><input name="task" required placeholder="Add a channel task…" aria-label="New channel task"><button class="primary">Add</button></form></div></section></div>`}
function tasks(){return heading('Tasks','',false)+[...active().map(v=>({name:v.title,tasks:v.tasks,id:v.id})),{name:'Channel',tasks:state.channel.tasks||[],id:'channel'}].map(g=>`<div class="section-heading"><h2>${esc(g.name)}</h2>${g.id!=='channel'?`<a class="text-link" href="#video/${g.id}">Open project</a>`:''}</div><div class="panel">${taskRows(g.tasks,g.id)||'<p class="muted">No tasks yet.</p>'}<form class="inline-add" data-add-task="${g.id}"><input name="task" required placeholder="Add a task…" aria-label="New task"><button class="primary">Add</button></form></div>`).join('')}
function render(){if(['learnings','directions'].includes(location.hash.slice(1).split('/')[0])){location.hash='notebook';return}const hash=location.hash.slice(1)||'overview';view=hash.split('/')[0];renderedId=hash.split('/')[1]||'';$('#nav').innerHTML=[['overview','◫','Overview'],['videos','▤','Videos'],['results','','Results'],['notebook','','Notebook'],['calendar','▦','Calendar'],['tasks','☑','Tasks'],['channel','◎','Channel'],['archive','▱','Archive'],['trash','','Trash']].map(([k,i,n])=>`<a href="#${k}" class="${view===k||(view==='video'&&k==='videos')?'active':''}">${n}</a>`).join('');$('#crumb').textContent=({overview:'Overview',videos:'Videos',video:'Video project',calendar:'Calendar',tasks:'Tasks',channel:'Channel',archive:'Archive',trash:'Trash',results:'Results',notebook:'Notebook'})[view]||'Overview';let html;if(view==='video'){const v=state.videos.find(v=>v.id===hash.split('/')[1]);html=v?detail(v):'<div class="empty">Project not found. <a href="#videos">Back to videos</a></div>'}else html=view==='trash'?heading('Trash','Deleted videos can be restored.','')+`<div class="grid">${state.videos.filter(v=>v.deleted).map(v=>card(v)).join('')||'<p class="muted">Trash is empty.</p>'}</div>`:view==='notebook'?NB.render():view==='results'?results():view==='videos'?videos():view==='calendar'?calendar():view==='channel'?channel():view==='tasks'?tasks():view==='archive'?heading('Archive','',false)+(state.videos.some(v=>v.archived&&!v.deleted)?`<div class="grid">${state.videos.filter(v=>v.archived&&!v.deleted).map(v=>card(v)).join('')}</div>`:'<div class="empty">No archived projects.</div>'):overview();$('#main').innerHTML=html;bind()}
function current(){return view==='channel'?state.channel:state.videos.find(v=>v.id===renderedId)}
function collect(){const o=current();if(!o)return;document.querySelectorAll('[data-field]').forEach(el=>o[el.dataset.field]=el.multiple?Array.from(el.selectedOptions,o=>o.value):el.value)}
async function persist(scope){if(scope==='channel')state.channel=await api('channel',state.channel);else{const i=state.videos.findIndex(v=>v.id===scope);state.videos[i]=await api('video',state.videos[i])}}
async function saveCurrent(){collect();await persist(view==='channel'?'channel':current().id);dirty=false;toast('Saved');const label=$('.save-state');if(label)label.textContent='Saved'}
function create(stage='Idea'){creatingStage=stage;for(const k of ['learning','direction','hypothesis'])delete $('#create-form').dataset[k];$('#create-form').reset();$('#new-pillar').innerHTML='<option value="">Choose a pillar</option>'+(state.channel.pillars||'').split('\n').filter(Boolean).map(p=>`<option>${esc(p)}</option>`).join('');$('#create-dialog').showModal();$('#new-title').focus()}
async function guarded(fn){if(busy)return;busy=true;try{await fn()}catch(e){toast(e.message)}finally{busy=false}}
function bind(){
 $('#delete-video')?.addEventListener('click',()=>guarded(async()=>{collect();const v=current();v.deleted=true;await persist(v.id);dirty=false;location.hash='trash';toast('Video moved to Trash. Open it there to restore.')}));
 $('#restore-video')?.addEventListener('click',()=>guarded(async()=>{collect();const v=current();v.deleted=false;await persist(v.id);dirty=false;render();toast('Video restored')}));

 NB.bind();
 bindLearning();
 document.querySelectorAll('[draggable]').forEach(c=>c.ondragstart=e=>{e.dataTransfer.setData('text/plain',c.dataset.video);e.dataTransfer.effectAllowed='move'});
 document.querySelectorAll('[data-drop-stage]').forEach(c=>{c.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move'};c.ondrop=e=>{e.preventDefault();const v=state.videos.find(v=>v.id===e.dataTransfer.getData('text/plain'));if(v)guarded(async()=>{const previous=v.stage;v.stage=c.dataset.dropStage;try{await persist(v.id);render();toast('Moved to '+v.stage)}catch(err){v.stage=previous;throw err}})}});
document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>create(b.dataset.stage));document.querySelectorAll('[data-field]').forEach(e=>e.oninput=()=>{dirty=true;const label=$('.save-state');if(label)label.textContent='Unsaved changes'});$('#save-video')?.addEventListener('click',()=>guarded(saveCurrent));$('#save-channel')?.addEventListener('click',()=>guarded(saveCurrent));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{collect();tab=b.dataset.tab;render();if(dirty&&$('.save-state'))$('.save-state').textContent='Unsaved changes'});$('#archive-video')?.addEventListener('click',()=>guarded(async()=>{collect();const v=current();v.archived=!v.archived;await persist(v.id);dirty=false;location.hash=v.archived?'archive':'videos'}));document.querySelectorAll('[data-task],[data-remove]').forEach(el=>el.addEventListener(el.matches('input')?'change':'click',()=>guarded(async()=>{collect();const scope=el.dataset.scope,o=scope==='channel'?state.channel:state.videos.find(v=>v.id===scope);if(el.dataset.remove!==undefined)o.tasks.splice(+el.dataset.remove,1);else o.tasks[+el.dataset.task].done=el.checked;await persist(scope);dirty=false;render()})));document.querySelectorAll('[data-add-task]').forEach(f=>f.onsubmit=e=>{e.preventDefault();guarded(async()=>{collect();const scope=f.dataset.addTask,o=scope==='channel'?state.channel:state.videos.find(v=>v.id===scope),value=f.elements.task.value.trim();if(!value)return;(o.tasks||=[]).push({text:value,done:false});await persist(scope);dirty=false;render()})});document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+ +b.dataset.month,1);render()});$('#month-today')?.addEventListener('click',()=>{month=new Date();render()});$('#filter')?.addEventListener('input',e=>document.querySelectorAll('.video-card').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(e.target.value.toLowerCase())))}
$('#create-form').onsubmit=e=>{e.preventDefault();guarded(async()=>{if(dirty)await saveCurrent();const v=await api('video',{title:$('#new-title').value.trim(),pillar:$('#new-pillar').value,date:$('#new-date').value,stage:creatingStage,sourceLearningId:$('#create-form').dataset.learning||'',directionId:$('#create-form').dataset.direction||'',hypothesis:$('#create-form').dataset.hypothesis||'',hook:'',notes:'',script:'',titles:'',thumbnail:'',sponsor:'',archived:false,tasks:['Define the hook','Research & prototype','Write the script','Record footage','Edit the video','Create title & thumbnail','Upload & publish'].map(text=>({text,done:false}))});state.videos.push(v);$('#create-dialog').close();tab='brief';location.hash='video/'+v.id;toast('Video created')})};
$('#cancel-create').onclick=()=>$('#create-dialog').close();
function search(){const q=$('#search-input').value.toLowerCase();$('#search-results').innerHTML=state.videos.filter(v=>!v.deleted&&(v.title+' '+v.hook+' '+v.pillar).toLowerCase().includes(q)).map(v=>`<a href="#video/${v.id}">${esc(v.title)} <span class="pill">${esc(v.stage)}${v.archived?' · Archived':''}</span></a>`).join('')||'<p class="muted">No matching videos.</p>';$('#search-results').querySelectorAll('a').forEach(a=>a.onclick=()=>$('#search-dialog').close())}
function openSearch(){$('#search-dialog').showModal();$('#search-input').value='';search();$('#search-input').focus()}
$('#search-open').onclick=openSearch;$('#search-input').oninput=search;$('#close-search').onclick=()=>$('#search-dialog').close();document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();openSearch()}if((e.metaKey||e.ctrlKey)&&e.key==='s'&&['video','channel'].includes(view)){e.preventDefault();guarded(saveCurrent)}});
// Save before in-app navigation; do not silently discard a draft on save failure.
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a&&dirty){e.preventDefault();guarded(async()=>{await saveCurrent();location.hash=a.getAttribute('href')})}},true);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
window.addEventListener('hashchange',async()=>{if(dirty){try{await saveCurrent()}catch(e){toast(e.message);history.replaceState(null,'','#'+view+(renderedId?'/'+renderedId:''));return}}tab=location.hash.split('/')[2]==='review'?'review':'brief';render()});
api('workspace').then(s=>{state=s;NB.load(s.notebook);tab=location.hash.split('/')[2]==='review'?'review':'brief';state.channel.learnings ||= [];state.channel.directions ||= [];const local=document.querySelector('.sidebar-bottom');local.title=state.workspacePath;local.querySelector('small').textContent=state.workspacePath||'Local folder';render()}).catch(e=>$('#main').innerHTML=`<div class="empty">Could not open the workspace: ${esc(e.message)}. Restart the local server and reload.</div>`);

function relationField(label,key,items,value){return `<label>${label}<select data-field="${key}"><option value="">None</option>${items.map(x=>`<option value="${x.id}" ${value===x.id?'selected':''}>${esc(x.title)}${x.archived?' (archived)':''}</option>`).join('')}</select></label>`}
function choice(label,key,value,options){return `<label>${label}<select data-field="${key}">${options.map(x=>`<option ${value===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`}
function review(v){return `<div class="section-heading" style="margin-top:0"><h2>Results and review</h2><button class="secondary" data-review-note="${v.id}">Save as note</button></div><p class="muted">${esc(v.hypothesis||'No initial hypothesis recorded.')}</p><div class="review-fields">${choice('Review status','reviewStatus',v.reviewStatus||'Not reviewed',['Not reviewed','In progress','Reviewed'])}${field('Reviewed on','reviewDate',v.reviewDate,'date')}${choice('Measurement window','window',v.window||'7 days',['24 hours','7 days','28 days','Lifetime'])}${field('Measured on','measuredOn',v.measuredOn,'date')}${field('Views','views',v.views,'number')}${field('Impressions CTR (%)','ctr',v.ctr,'number')}${field('Average viewed (%)','retention',v.retention,'number')}${field('Production hours','effort',v.effort,'number')}</div>${field('What happened? · audience response, retention moments, comments','observations',v.observations)}${field('Why do you think it happened? · possible explanations','interpretation',v.interpretation)}${field('What did you learn while making it?','productionLearning',v.productionLearning)}${field('What would you repeat or change?','nextTest',v.nextTest)}${choice('Pursue this topic or format again?','repeat',v.repeat||'Undecided',['Undecided','Yes','With changes','No'])}<p class="muted">Metrics are entered manually. Compare videos over the same measurement window.</p>`}
function entryLinks(items,type){return items.length?items.map(x=>`<a class="entry-row" href="#${type}/${x.id}"><span>${esc(x.title)}</span><small>${esc(x.status||'')}${x.archived?' · Archived':''}</small></a>`).join(''):'<p class="muted">None yet.</p>'}
function videoLinks(items){return items.length?items.map(v=>`<a class="entry-row" href="#video/${v.id}"><span>${esc(v.title)}</span><small>${esc(v.stage)}${v.archived?' · Archived':''}</small></a>`).join(''):'<p class="muted">None yet.</p>'}
function overview(){return heading('Overview')+`<div class="section-heading"><h2>Notes</h2><a href="#notebook" class="text-link">Open notebook</a></div>${NB.recent()}<div class="section-heading"><h2>Videos in progress</h2><a href="#videos" class="text-link">All videos</a></div><div class="grid">${active().filter(v=>v.stage!=='Published').map(v=>card(v)).join('')||'<p class="muted">No active videos.</p>'}</div>`}
function results(){return heading('Published results','Manual snapshots. Compare the same measurement window; blank values mean not recorded.',false)+`<div class="filters"><label>Measurement window<select id="results-window"><option>7 days</option><option>24 hours</option><option>28 days</option><option>Lifetime</option></select></label></div><div class="table-scroll"><table><thead><tr><th>Video</th><th>Measured</th><th>Views</th><th>CTR</th><th>Avg. viewed</th><th>Hours</th><th>Review</th></tr></thead><tbody id="results-rows"></tbody></table></div>`}
function resultRows(){const period=$('#results-window').value;$('#results-rows').innerHTML=active().filter(v=>v.stage==='Published'&&(v.window||'7 days')===period).map(v=>`<tr><td><a href="#video/${v.id}/review">${esc(v.title)}</a></td><td>${v.measuredOn?pretty(v.measuredOn):'—'}</td>${['views','ctr','retention','effort'].map(k=>`<td>${v[k]!==undefined&&v[k]!==''?esc(v[k])+(['ctr','retention'].includes(k)?'%':''):'—'}</td>`).join('')}<td>${esc(v.reviewStatus||'Not reviewed')}</td></tr>`).join('')||'<tr><td colspan="7">No published videos in this window.</td></tr>'}
function bindLearning(){$('#results-window')?.addEventListener('change',resultRows);if($('#results-window'))resultRows()}
