const NB=(()=>{
 let data={revision:0,notes:[],edges:[],strokes:[]},changed=false,saving=false,timer,tool='move',first=null,history=[],filter='',camera={x:60,y:60,z:1},expanded=false,libraryOpen=false,selected=null,space=false,gesture=null,pointers=new Map();
 const id=()=>crypto.randomUUID().replaceAll('-','');
 const title=n=>n.title||n.body.split('\n')[0].slice(0,70)||'Untitled note';
 const noteBy=id=>data.notes.find(n=>n.id===id);
 function load(d){if(d)data=d;let migrated=false;for(const kind of ['learnings','directions'])for(const entry of state.channel[kind]||[]){const key=kind+':'+entry.id;if(data.notes.some(n=>n.legacySource===key))continue;data.notes.push({id:id(),legacySource:key,title:entry.title||'',body:[entry.question,entry.notes,entry.observation,entry.interpretation,entry.nextTest,entry.evidence].filter(Boolean).join('\n\n'),tags:'',color:'plain',videoIds:[...new Set([...(entry.videoIds||[]),...state.videos.filter(v=>v.directionId===entry.id||v.sourceLearningId===entry.id).map(v=>v.id)])],x:0,y:0,onBoard:false});migrated=true}if(migrated)edit();try{const c=JSON.parse(localStorage.getItem('board-camera:'+state.workspacePath));if(c&&[c.x,c.y,c.z].every(Number.isFinite)&&c.z>=.1&&c.z<=4)camera=c}catch{}}
 function snapshot(){history.push(JSON.stringify(data));if(history.length>30)history.shift()}
 function edit(){changed=true;clearTimeout(timer);timer=setTimeout(save,500);status()}
 function status(){document.querySelectorAll('.nb-status').forEach(e=>e.textContent=saving?'Saving…':changed?'Unsaved':'Saved')}
 async function save(){clearTimeout(timer);if(saving||!changed)return;saving=true;changed=false;status();try{const response=await api('notebook',JSON.parse(JSON.stringify(data)));data.revision=response.revision}catch(e){changed=true;toast(e.message);saving=false;status();return}saving=false;status();if(changed)save()}
 function noteCard(n){return `<button class="note-preview color-${n.color}" data-edit-note="${n.id}">${n.title?`<strong>${esc(n.title)}</strong>`:''}${images(n.images)}<p>${esc(n.body.slice(0,220))}</p><small>${esc(n.tags)}</small></button>`}
 function recent(){return `<div class="grid">${data.notes.slice().reverse().slice(0,6).map(noteCard).join('')||'<p class="muted">No notes yet. Add one from a video or the notebook.</p>'}</div>`}
 function videoNotes(v){return `<div class="section-heading" style="margin-top:0"><h2>Notes</h2><button class="secondary" data-new-note="${v.id}">Add note</button></div><div class="note-list">${data.notes.filter(n=>n.videoIds.includes(v.id)).map(noteCard).join('')||'<p class="muted">No notes attached to this video.</p>'}</div><a class="text-link" href="#notebook">Arrange notes in the notebook</a>`}
 function render(){return `<section id="notebook-root" class="${expanded?'expanded':''}"><div class="canvas-top"><div class="canvas-tools"><button class="secondary" id="nb-library" aria-pressed="${libraryOpen}" title="Note library">Notes</button><button class="secondary" data-new-note="" title="New note (N)">＋</button><button class="secondary" id="nb-pen" aria-pressed="${tool==='draw'}" title="Pen (P) / Select (V)">✎</button><span class="nb-status">${changed?'Unsaved':'Saved'}</span></div><button class="secondary" id="nb-expand" title="Expand canvas (F)">${expanded?'Exit full screen':'Full screen'}</button></div><aside class="note-library ${libraryOpen?'open':''}"><input id="note-filter" aria-label="Search notes and tags" placeholder="Search notes or tags…" value="${esc(filter)}"><div id="note-library"></div></aside><div id="board-scroll" tabindex="0" aria-label="Notebook canvas. Drag blank space to pan. Pinch or Control plus scroll to zoom."><div id="note-board"><svg id="board-ink" width="1" height="1"></svg><div id="board-cards"></div></div></div><div class="canvas-bottom"><span id="nb-help">Drag paper to pan · Double-click to write · Drag a note’s dot to connect</span><div class="canvas-tools"><button id="nb-undo" title="Undo (⌘Z)">↶</button><button id="nb-fit" title="Fit all notes">Fit</button><button id="nb-minus" aria-label="Zoom out">−</button><button id="nb-zoom" title="Reset zoom">100%</button><button id="nb-plus" aria-label="Zoom in">＋</button><button id="nb-save" title="Save notebook">Save</button></div></div></section>`}
 function library(){const el=$('#note-library');if(!el)return;el.innerHTML=data.notes.filter(n=>(n.title+' '+n.body+' '+n.tags).toLowerCase().includes(filter.toLowerCase())).map(n=>`<div class="library-note"><button data-edit-note="${n.id}">${esc(title(n))}</button><small>${esc(n.tags)}</small><button class="text-link" data-place-note="${n.id}">${n.onBoard?'Locate':'Add to board'}</button></div>`).join('')||'<p class="muted">No matching notes.</p>';bindNoteButtons(el)}
 function lines(){const svg=$('#board-ink');if(!svg)return;svg.innerHTML=data.edges.map((e,i)=>{let a=noteBy(e.from),b=noteBy(e.to);if(!a?.onBoard||!b?.onBoard)return '';return `<line class="${selected?.kind==='edge'&&selected.index===i?'ink-selected':''}" data-edge="${i}" x1="${a.x+220}" y1="${a.y+60}" x2="${b.x}" y2="${b.y+60}"/>`}).join('')+data.strokes.map((s,i)=>`<polyline class="${selected?.kind==='stroke'&&selected.index===i?'ink-selected':''}" data-stroke="${i}" points="${s.points.map(p=>p.join(',')).join(' ')}"/>`).join('');if(gesture?.kind==='connect'){const n=noteBy(gesture.id);svg.innerHTML+=`<line class="connection-preview" x1="${n.x+220}" y1="${n.y+60}" x2="${gesture.point.x}" y2="${gesture.point.y}"/>`}}
 function draw(){const cards=$('#board-cards');if(!cards)return;lines();cards.innerHTML=data.notes.filter(n=>n.onBoard).map(n=>`<article tabindex="0" class="board-note color-${n.color} ${selected?.id===n.id?'connecting':''}" style="left:${n.x}px;top:${n.y}px" data-note="${n.id}" aria-label="${esc(title(n))}. Drag to move; Enter to edit."><div class="note-handle"><span>${esc(n.tags)||'Note'}</span><button data-unplace="${n.id}" title="Remove from board" aria-label="Remove from board">×</button></div><div class="note-content">${n.title?`<strong>${esc(n.title)}</strong>`:''}${images(n.images)}<p>${esc(n.body.slice(0,500))}</p></div><small>${n.videoIds.map(i=>{let v=state.videos.find(v=>v.id===i);return v?`<a href="#video/${v.id}">${esc(v.title)}</a>`:''}).join(' · ')}</small><button class="note-port" data-port="${n.id}" aria-label="Connect ${esc(title(n))}" title="Drag to another note"></button></article>`).join('');cards.querySelectorAll('[data-unplace]').forEach(b=>b.onclick=()=>{snapshot();noteBy(b.dataset.unplace).onBoard=false;edit();draw();library()});cards.querySelectorAll('.board-note').forEach(n=>n.ondblclick=e=>{if(e.target.closest('button,a'))return;e.stopPropagation();editor(n.dataset.note)});transform()}
 function center(){const el=$('#board-scroll');return {x:((el?.clientWidth||600)/2-camera.x)/camera.z-110,y:((el?.clientHeight||500)/2-camera.y)/camera.z-80}}
 function transform(){const board=$('#note-board'),viewport=$('#board-scroll');if(!board)return;board.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.z})`;viewport.style.backgroundSize=`${24*camera.z}px ${24*camera.z}px`;viewport.style.backgroundPosition=`${camera.x}px ${camera.y}px`;viewport.dataset.pen=tool==='draw';$('#nb-zoom').textContent=Math.round(camera.z*100)+'%';try{localStorage.setItem('board-camera:'+state.workspacePath,JSON.stringify(camera))}catch{}}
 function world(e){const r=$('#board-scroll').getBoundingClientRect();return {x:(e.clientX-r.left-camera.x)/camera.z,y:(e.clientY-r.top-camera.y)/camera.z}}
 function zoom(z,x,y){const el=$('#board-scroll');x??=el.clientWidth/2;y??=el.clientHeight/2;z=Math.min(4,Math.max(.1,z));camera.x=x-(x-camera.x)*z/camera.z;camera.y=y-(y-camera.y)*z/camera.z;camera.z=z;transform()}
 function fit(){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const include=(x,y)=>{minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)};data.notes.filter(n=>n.onBoard).forEach(n=>{include(n.x,n.y);include(n.x+220,n.y+300)});data.strokes.forEach(s=>s.points.forEach(p=>include(...p)));if(!Number.isFinite(minX)){camera={x:60,y:60,z:1};transform();return}const el=$('#board-scroll');camera.z=Math.max(.1,Math.min(1.5,(el.clientWidth-100)/(maxX-minX||1),(el.clientHeight-100)/(maxY-minY||1)));camera.x=el.clientWidth/2-(minX+maxX)/2*camera.z;camera.y=el.clientHeight/2-(minY+maxY)/2*camera.z;transform()}
 function undo(){if(!history.length)return;const revision=data.revision;data=JSON.parse(history.pop());data.revision=revision;selected=null;edit();draw();library()}
 function expand(){expanded=!expanded;$('#notebook-root').classList.toggle('expanded',expanded);$('#nb-expand').textContent=expanded?'Exit full screen':'Full screen';transform()}
 function bindNoteButtons(root){root.querySelectorAll('[data-edit-note]').forEach(b=>b.onclick=()=>editor(b.dataset.editNote));root.querySelectorAll('[data-place-note]').forEach(b=>b.onclick=()=>{const n=noteBy(b.dataset.placeNote),el=$('#board-scroll');if(!n.onBoard){snapshot();n.onBoard=true;Object.assign(n,center());edit();draw();library()}camera.x=el.clientWidth/2-(n.x+110)*camera.z;camera.y=el.clientHeight/2-(n.y+100)*camera.z;selected={kind:'note',id:n.id};draw()})}
 function bindCanvas(){const el=$('#board-scroll');library();draw();$('#nb-library').onclick=()=>{libraryOpen=!libraryOpen;$('.note-library').classList.toggle('open',libraryOpen);$('#nb-library').setAttribute('aria-pressed',libraryOpen)};$('#nb-pen').onclick=()=>{tool=tool==='draw'?'move':'draw';$('#nb-pen').setAttribute('aria-pressed',tool==='draw');$('#nb-help').textContent=tool==='draw'?'Draw on paper · Hold Space to pan · V to stop drawing':'Drag paper to pan · Double-click to write · Drag a note’s dot to connect';transform()};$('#nb-save').onclick=save;$('#nb-undo').onclick=undo;$('#nb-expand').onclick=expand;$('#nb-fit').onclick=fit;$('#nb-plus').onclick=()=>zoom(camera.z*1.2);$('#nb-minus').onclick=()=>zoom(camera.z/1.2);$('#nb-zoom').onclick=()=>zoom(1);$('#note-filter').oninput=e=>{filter=e.target.value;library()};el.onwheel=e=>{e.preventDefault();const r=el.getBoundingClientRect(),factor=e.deltaMode===1?16:e.deltaMode===2?el.clientHeight:1;if(e.ctrlKey||e.metaKey)zoom(camera.z*Math.exp(-e.deltaY*factor*.01),e.clientX-r.left,e.clientY-r.top);else{camera.x-=e.deltaX*factor;camera.y-=e.deltaY*factor;transform()}};el.ondblclick=e=>{if(!e.target.closest('.board-note'))editor('','',world(e))};el.onpointerdown=e=>{if(e.target.closest('a,[data-unplace]')||e.button===2)return;e.preventDefault();el.focus();el.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){if(gesture?.kind==='draw'||gesture?.kind==='note')edit();const [a,b]=[...pointers.values()],r=el.getBoundingClientRect();gesture={kind:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),z:camera.z,wx:((a.x+b.x)/2-r.left-camera.x)/camera.z,wy:((a.y+b.y)/2-r.top-camera.y)/camera.z};return}const n=e.target.closest('[data-note]'),port=e.target.closest('[data-port]'),ink=e.target.closest('[data-edge],[data-stroke]');if(space||e.button===1){gesture={kind:'pan',x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};return}if(port){gesture={kind:'connect',id:port.dataset.port,point:world(e)};return}if(n){selected={kind:'note',id:n.dataset.note};snapshot();const note=noteBy(n.dataset.note);gesture={kind:'note',id:note.id,x:e.clientX,y:e.clientY,nx:note.x,ny:note.y};draw();return}if(tool==='draw'){snapshot();const p=world(e);data.strokes.push({points:[[p.x,p.y]]});gesture={kind:'draw',index:data.strokes.length-1};return}if(ink){selected={kind:ink.dataset.edge!==undefined?'edge':'stroke',index:+(ink.dataset.edge??ink.dataset.stroke)};draw();return}selected=null;draw();gesture={kind:'pan',x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y}};
 el.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!gesture)return;let g=gesture;if(g.kind==='pinch'&&pointers.size===2){let [a,b]=[...pointers.values()],r=el.getBoundingClientRect();camera.z=Math.min(4,Math.max(.1,g.z*Math.hypot(a.x-b.x,a.y-b.y)/(g.distance||1)));camera.x=(a.x+b.x)/2-r.left-g.wx*camera.z;camera.y=(a.y+b.y)/2-r.top-g.wy*camera.z;transform()}else if(g.kind==='pan'){camera.x=g.cx+e.clientX-g.x;camera.y=g.cy+e.clientY-g.y;transform()}else if(g.kind==='note'){const n=noteBy(g.id);n.x=g.nx+(e.clientX-g.x)/camera.z;n.y=g.ny+(e.clientY-g.y)/camera.z;const card=el.querySelector(`[data-note="${n.id}"]`);card.style.left=n.x+'px';card.style.top=n.y+'px';lines()}else if(g.kind==='connect'){g.point=world(e);lines()}else if(g.kind==='draw'){const p=world(e),s=data.strokes[g.index];if(s.points.length<19000)s.points.push([p.x,p.y]);lines()}};
 const end=e=>{pointers.delete(e.pointerId);const g=gesture;if(!g)return;if(g.kind==='connect'&&e.type!=='pointercancel'){let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-note]')?.dataset.note;if(target&&target!==g.id&&!data.edges.some(x=>x.from===g.id&&x.to===target||x.to===g.id&&x.from===target)){snapshot();data.edges.push({from:g.id,to:target});edit()}}if(g.kind==='draw'||g.kind==='note')edit();gesture=null;if(pointers.size===1){let p=[...pointers.values()][0];gesture={kind:'pan',x:p.x,y:p.y,cx:camera.x,cy:camera.y}}draw()};el.onpointerup=end;el.onpointercancel=end;el.onlostpointercapture=e=>{if(pointers.has(e.pointerId))end(e)};
 }
 function editor(nid='',videoId='',position=null,seed={}){let n=noteBy(nid),pendingImages=[...(n?.images||[])],dialog=$('#note-editor');if(!dialog){dialog=document.createElement('dialog');dialog.id='note-editor';document.body.append(dialog)}dialog.innerHTML=`<form id="note-form"><h2>${n?'Edit note':'New note'}</h2><label>Title (optional)<input name="title" value="${esc(n?.title||seed.title||'')}"></label><label>Note<textarea name="body" class="note-writing" placeholder="Write…">${esc(n?.body||seed.body||'')}</textarea></label><div id="note-images">${images(pendingImages)}</div><div class="image-actions"><label class="secondary">Add image<input id="note-image-input" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></label><button type="button" class="secondary" id="note-sketch">Sketch</button></div><div class="review-fields"><label>Tags (comma-separated)<input name="tags" value="${esc(n?.tags||'')}"></label><label>Colour<select name="color">${['plain','yellow','blue','pink','green'].map(c=>`<option ${n?.color===c?'selected':''}>${c}</option>`).join('')}</select></label></div><label>Attached videos (optional)<select name="videos" multiple size="3">${state.videos.map(v=>`<option value="${v.id}" ${(n?.videoIds||seed.videoIds||[videoId]).includes(v.id)?'selected':''}>${esc(v.title)}</option>`).join('')}</select></label><div class="dialog-actions"><button type="button" id="cancel-note" class="secondary">Cancel</button><button class="primary">Save note</button></div></form>`;dialog.showModal();$('#note-image-input').onchange=e=>attachImage(e.target.files[0],a=>{pendingImages.push(a);$('#note-images').innerHTML=images(pendingImages)});$('#note-sketch').onclick=()=>sketch(a=>{pendingImages.push(a);$('#note-images').innerHTML=images(pendingImages)});dialog.querySelector('[name=body]').focus();$('#cancel-note').onclick=()=>dialog.close();$('#note-form').onsubmit=e=>{e.preventDefault();let f=e.target;if(!f.elements.title.value.trim()&&!f.elements.body.value.trim()&&!pendingImages.length){toast('Write a note or a title first.');return}snapshot();if(!n){const origin=position||center();n={id:id(),x:origin.x,y:origin.y,onBoard:view==='notebook'};data.notes.push(n)}Object.assign(n,{images:pendingImages,title:f.elements.title.value,body:f.elements.body.value,tags:f.elements.tags.value,color:f.elements.color.value,videoIds:Array.from(f.elements.videos.selectedOptions,o=>o.value)});edit();dialog.close();if(view==='notebook'){draw();library()}else{collect();render()}}}
 function bind(){
 document.querySelectorAll('[data-review-note]').forEach(b=>b.onclick=()=>guarded(async()=>{await saveCurrent();let v=state.videos.find(v=>v.id===b.dataset.reviewNote);editor('',v.id,null,{title:'Review: '+v.title,body:[['Initial idea',v.hypothesis],['What happened',v.observations],['Possible explanation',v.interpretation],['Making the video',v.productionLearning],['Try next',v.nextTest]].filter(x=>x[1]).map(x=>x[0]+'\n'+x[1]).join('\n\n')})}));
 document.querySelectorAll('[data-entry-note]').forEach(b=>b.onclick=()=>guarded(async()=>{await saveCurrent();const entry=current();editor('',entry.videoIds?.[0]||'',null,{title:entry.title,videoIds:entry.videoIds||[],body:[entry.question,entry.notes,entry.observation,entry.interpretation,entry.nextTest,entry.evidence].filter(Boolean).join('\n\n')})}));
 document.querySelectorAll('[data-video-image]').forEach(i=>i.onchange=e=>attachImage(e.target.files[0],async a=>{collect();const v=state.videos.find(v=>v.id===i.dataset.videoImage);(v.images||=[]).push(a);dirty=true;await persist(v.id);dirty=false;render()}));
 document.querySelectorAll('[data-video-sketch]').forEach(b=>b.onclick=()=>sketch(async a=>{collect();const v=state.videos.find(v=>v.id===b.dataset.videoSketch);(v.images||=[]).push(a);dirty=true;await persist(v.id);dirty=false;render()}));
document.querySelectorAll('[data-new-note]').forEach(b=>b.onclick=()=>editor('',b.dataset.newNote));bindNoteButtons($('#main'));if(view!=='notebook')return;bindCanvas()}

 function images(items=[]){return items.filter(a=>/^\/assets\/[a-f0-9]{32}\.(png|jpg|webp|gif)$/.test(a.path)).map(a=>`<img class="note-image" src="${esc(a.path)}" alt="${esc(a.name)}">`).join('')}
 function videoImages(v){return `<div class="image-actions"><label class="secondary">Upload thumbnail / reference<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-video-image="${v.id}" hidden></label><button class="secondary" data-video-sketch="${v.id}">Sketch thumbnail</button></div><div class="image-gallery">${(v.images||[]).map(a=>`<figure>${images([a])}<figcaption>${esc(a.name)}</figcaption></figure>`).join('')}</div>`}
 async function attachImage(file,callback){if(!file)return;if(file.size>10000000){toast('Image must be under 10 MB');return}try{const encoded=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});let a=await api('image',{name:file.name,data:encoded});await callback(a);toast('Image added')}catch(e){toast(e.message||'Could not add image')}}
 function sketch(callback){let d=document.createElement('dialog');d.className='sketch-dialog';d.innerHTML=`<h2>Thumbnail sketch</h2><div class="nb-toolbar"><label>Ink <input type="color" id="sketch-color" value="#222222"></label><label>Width <input type="range" id="sketch-width" min="2" max="30" value="5"></label><button class="secondary" id="sketch-undo">Undo stroke</button></div><canvas width="1280" height="720" id="sketch-canvas" aria-label="Draw thumbnail sketch with mouse or pen"></canvas><div class="dialog-actions"><button class="secondary" id="sketch-cancel">Cancel</button><button class="primary" id="sketch-save">Save sketch</button></div>`;document.body.append(d);d.showModal();const canvas=d.querySelector('canvas'),ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,1280,720);let undo=[],drawing=false;const point=e=>{let r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*1280/r.width,(e.clientY-r.top)*720/r.height]};canvas.onpointerdown=e=>{e.preventDefault();undo.push(ctx.getImageData(0,0,1280,720));if(undo.length>15)undo.shift();drawing=true;canvas.setPointerCapture(e.pointerId);ctx.strokeStyle=d.querySelector('#sketch-color').value;ctx.lineWidth=+d.querySelector('#sketch-width').value;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(...point(e))};canvas.onpointermove=e=>{if(drawing){ctx.lineTo(...point(e));ctx.stroke()}};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;d.querySelector('#sketch-undo').onclick=()=>{if(undo.length)ctx.putImageData(undo.pop(),0,0)};d.querySelector('#sketch-cancel').onclick=()=>{d.close();d.remove()};d.querySelector('#sketch-save').onclick=async e=>{e.target.disabled=true;try{const image=await api('image',{name:'Thumbnail sketch.png',data:canvas.toDataURL('image/png').split(',')[1]});await callback(image);d.close();d.remove();toast('Sketch saved')}catch(err){e.target.disabled=false;toast(err.message)}};d.addEventListener('close',()=>d.remove())}
 window.addEventListener('keydown',e=>{if(view!=='notebook'||document.querySelector('dialog[open]')||e.target.closest('input,textarea,select'))return;if(e.key==='Escape'){tool='move';selected=null;if(expanded)expand();draw();return}if(e.code==='Space'){e.preventDefault();space=true}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return}if(e.metaKey||e.ctrlKey)return;if(e.key.toLowerCase()==='f')expand();if(e.key.toLowerCase()==='n')editor();if(e.key==='+'||e.key==='=')zoom(camera.z*1.2);if(e.key==='-')zoom(camera.z/1.2);if(e.key==='0')fit();if(e.key.toLowerCase()==='p'||e.key.toLowerCase()==='v'){tool=e.key.toLowerCase()==='p'?'draw':'move';$('#nb-pen').setAttribute('aria-pressed',tool==='draw');transform()}if(e.key==='Enter'&&selected?.kind==='note')editor(selected.id);if(['Delete','Backspace'].includes(e.key)&&selected){e.preventDefault();snapshot();if(selected.kind==='note')noteBy(selected.id).onBoard=false;else data[selected.kind==='edge'?'edges':'strokes'].splice(selected.index,1);selected=null;edit();draw();library()}});
 window.addEventListener('keyup',e=>{if(e.code==='Space')space=false});window.addEventListener('blur',()=>space=false);
 window.addEventListener('beforeunload',e=>{if(changed||saving||$('#note-editor')?.open){e.preventDefault();e.returnValue=''}});
 return {load,render,bind,videoNotes,recent,videoImages};
})();
